Repository Ann040294/mmmsg, pull requests merged in 2025-03, with the labels that each got.

#153 Input: исправил баг с шириной
  packages/ui-kit/Input/Input.module.scss
Labels: DEV_REVIEW

#127 App: Список чатов. Infinite Scroll
  app/src/entities/compactMessage/api/getAllCompactMessages.ts
  app/src/shared/lib/hooks/useIncreaseOrDecrease.ts
  app/src/shared/lib/hooks/useInfiniteScroll.ts
  app/src/widgets/MessageList/ui/MessageList.tsx
Labels: LEAD_REVIEW

#95 (Msg) Text Viewer
  app/src/pages/test/index.tsx
  app/src/pages/test/ui/TestTextViewer.tsx
  packages/ui-kit/TextViewer/TextViewer.module.scss
  packages/ui-kit/TextViewer/TextViewer.tsx
  packages/ui-kit/TextViewer/index.ts
  packages/ui-kit/TextViewer/types.ts
  packages/ui-kit/index.ts
  packages/ui-kit/styles/_color.scss
  packages/ui-kit/styles/_textViewer.scss
Labels: MENTOR_REVIEW

#154 App: Список чатов. Поиск.
  app/src/entities/compactMessage/api/getAllCompactMessages.ts
  app/src/entities/compactMessage/api/searchCompactMessages.ts
  app/src/shared/lib/hooks/useCounter.ts
  app/src/shared/lib/hooks/useDebounce.ts
  app/src/shared/lib/hooks/useIncreaseOrDecrease.ts
  app/src/shared/lib/hooks/useInfiniteScroll.ts
  app/src/shared/lib/hooks/useIsToggled.ts
  app/src/shared/lib/utils/getPaginationArray.ts
  app/src/widgets/MessageList/ui/MessageList.tsx
Labels: LEAD_REVIEW

#158 Multi-lingual: подключение i18n
  app/src/index.tsx
  app/src/pages/home/ui/index.tsx
  app/src/pages/layout/ui/Navbar/Item/NavbarItem.tsx
  app/src/shared/config/routeConfig.ts
  app/src/shared/i18n/i18n.ts
  app/src/shared/i18n/index.ts
  app/src/shared/i18n/locales/en.json
  app/src/shared/i18n/locales/ru.json
  app/src/shared/ui/HeaderPage/HeaderPage.tsx
  app/src/widgets/MessageList/ui/MessageList.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: LEAD_REVIEW

#165 multi-lingual(Bugfix/163): добавил перевод роута
  app/src/pages/test/index.tsx
Labels: DEV_REVIEW
