Repository Ann040294/mmmsg, pull requests merged in 2025-04, with the labels that each got.

#159 App: Multi-outlet
  app/package.json
  app/src/app/App.tsx
  app/src/app/routes/AppRouter.tsx
  app/src/app/routes/config/routes.ts
  app/src/app/routes/config/types.ts
  app/src/app/routes/config/utils/removePropertyOutlet.ts
  app/src/app/routes/routes.ts
  app/src/app/routes/ui/Layout/CustomOutlet/CustomOutlet.tsx
  app/src/app/routes/ui/Layout/CustomOutlet/types.ts
  app/src/app/routes/ui/Layout/CustomOutlet/utils/getMatchingRoute.ts
  app/src/app/routes/ui/Layout/CustomOutlet/utils/getRoutePaths.ts
  app/src/app/routes/ui/Layout/CustomOutlet/utils/getRoutes.ts
  app/src/app/routes/ui/Layout/config/defaultConfig.ts
  app/src/app/routes/ui/Layout/index.tsx
  app/src/app/routes/ui/Layout/layout.module.scss
  app/src/pages/layout/index.ts
  app/src/shared/config/routeConfig.ts
  app/src/shared/i18n/locales/en.json
  app/src/shared/i18n/locales/ru.json
  app/src/widgets/Navbar/Item/NavbarItem.module.scss
  app/src/widgets/Navbar/Item/NavbarItem.tsx
  app/src/widgets/Navbar/Item/index.ts
  app/src/widgets/Navbar/Item/types.ts
  app/src/widgets/Navbar/Navbar.module.scss
  app/src/widgets/Navbar/Navbar.tsx
  app/src/widgets/Navbar/index.ts
  app/src/widgets/Navbar/utils/getKeyFromNavLinkArray.ts
  yarn.lock
Labels: LEAD_REVIEW

#164 (Msg) Actions
  app/src/pages/test/index.tsx
  app/src/pages/test/ui/TestActions.tsx
  packages/ui-kit/Actions/Actions.module.scss
  packages/ui-kit/Actions/Actions.tsx
  packages/ui-kit/Actions/index.ts
  packages/ui-kit/Actions/types.ts
  packages/ui-kit/index.ts
Labels: LEAD_REVIEW

#181 Input - bugfix(177-178): добавил дополнительные пропсы
  packages/ui-kit/Input/Input.tsx
Labels: DEV_REVIEW

#166 Input-bugfix(72-73-105): добавил дополнительные состояния input, исправил недочёты
  app/src/pages/test/ui/TestInputs.tsx
  packages/ui-kit/Input/Input.module.scss
  packages/ui-kit/Input/Input.tsx
Labels: LEAD_REVIEW

#182 App: Filler. Добавлена анимация рыбке
  app/src/shared/ui/Filler/Filler.module.scss
  app/src/shared/ui/Filler/Filler.tsx
  app/src/shared/ui/Fish/Fish.module.scss
  app/src/shared/ui/Fish/Fish.tsx
Labels: MENTOR_REVIEW, LEAD_REVIEW

#180 App: NotFound Page
  app/src/app/routes/config/routes.ts
  app/src/pages/not-found/index.tsx
  app/src/pages/not-found/ui/NotFoundPage.module.scss
  app/src/pages/not-found/ui/index.tsx
  app/src/shared/config/routeConfig.ts
  app/src/shared/i18n/locales/en.json
  app/src/shared/i18n/locales/ru.json
  app/src/shared/ui/Filler/Filler.tsx
Labels: LEAD_REVIEW

#198 App: Message List. Обернул получение данных в timer
  app/src/entities/compactMessage/api/getAllCompactMessages.ts
  app/src/entities/compactMessage/api/searchCompactMessages.ts
  app/src/pages/test/ui/TestSpinners.tsx
  app/src/shared/lib/hooks/useIsToggled.ts
  app/src/widgets/MessageList/ui/MessageList.module.scss
  app/src/widgets/MessageList/ui/MessageList.tsx
  packages/ui-kit/LinearLoader/LinearLoader.module.scss
  packages/ui-kit/LinearLoader/LinearLoader.tsx
  packages/ui-kit/Spinner/Spinner.tsx
  packages/ui-kit/index.ts
Labels: MENTOR_REVIEW

#185 App: Страница Profile
  app/src/app/routes/config/routes.ts
  app/src/app/routes/ui/Layout/layout.module.scss
  app/src/entities/user/api/user.ts
  app/src/entities/user/mock/userMock.ts
  app/src/entities/user/model/user.ts
  app/src/pages/profile/index.tsx
  app/src/pages/profile/ui/ProfileForm/ProfileForm.module.scss
  app/src/pages/profile/ui/ProfileForm/ProfileForm.tsx
  app/src/pages/profile/ui/ProfileForm/config/inputFields.ts
  app/src/pages/profile/ui/index.tsx
  app/src/shared/i18n/locales/en.json
  app/src/shared/i18n/locales/ru.json
  packages/ui-kit/index.ts
Labels: MENTOR_REVIEW

#201 App: Filler. Не растягивался на всю ширину
  app/src/pages/not-found/ui/index.tsx
  app/src/shared/config/routeConfig.ts
  app/src/shared/ui/Filler/Filler.module.scss
  app/src/shared/ui/Filler/Filler.tsx
Labels: LEAD_REVIEW

#188 App: Страница Регистрации(Скелет)
  app/src/app/routes/config/routes.ts
  app/src/pages/register/index.tsx
  app/src/pages/register/ui/config/registrationFields.ts
  app/src/pages/register/ui/index.tsx
  app/src/pages/register/ui/register.module.scss
  app/src/shared/i18n/locales/en.json
  app/src/shared/i18n/locales/ru.json
  packages/ui-kit/Checkbox/Checkbox.module.scss
  packages/ui-kit/Checkbox/Checkbox.tsx
  packages/ui-kit/Checkbox/index.ts
  packages/ui-kit/Input/Input.tsx
  packages/ui-kit/index.ts
Labels: LEAD_REVIEW

#204 App: RTK в Profile Page
  app/package.json
  app/src/app/App.tsx
  app/src/app/store/store.ts
  app/src/entities/user/api/slice.ts
  app/src/pages/not-found/ui/index.tsx
  app/src/pages/profile/ui/ProfileForm/ProfileForm.tsx
  app/src/shared/i18n/locales/en.json
  app/src/shared/i18n/locales/ru.json
  app/src/shared/lib/hooks/redux.ts
  app/src/shared/lib/slices/apiSlice.ts
  package-lock.json
  packages/ui-kit/package.json
  yarn.lock
Labels: LEAD_REVIEW

#183 Сообщение (Msg)
  app/src/pages/test/index.tsx
  app/src/pages/test/ui/TestMessage.tsx
  app/src/widgets/Message/Message.module.scss
  app/src/widgets/Message/Message.tsx
  app/src/widgets/Message/hooks/useMessageVariant.ts
  app/src/widgets/Message/index.ts
  app/src/widgets/Message/types.ts
Labels: LEAD_REVIEW

#208 🟠 Сообщение (Msg): Actions отображаются в другой стороне сообщения
  app/src/widgets/Message/Message.module.scss
  packages/ui-kit/TextViewer/TextViewer.module.scss
  packages/ui-kit/TextViewer/TextViewer.tsx
Labels: LEAD_REVIEW

#206 App: RTK на HomePage
  app/src/entities/compactMessage/api/slice.ts
  app/src/pages/profile/ui/ProfileForm/ProfileForm.tsx
  app/src/shared/lib/slices/apiSlice.ts
  app/src/widgets/MessageList/ui/MessageList.tsx
Labels: MENTOR_REVIEW, DEV_REVIEW
